### ISSUE TITLE
Get alpha_2 code by name of country using country_list countries_for_language

### ISSUE THREAD

**Issue by Avramo** [bulv1ne/country_list#89]
Hi ,
I use `country_list` and `countries_for_language` to get country names in Spanish by giving the `alpha_2` code.

Now, is there a built in function in this library that can o the opposite?
I want to take the country name with the exact spelling I got from  countries_for_language and use that to get the alpha_2 country code.

> For example:   

This code
`countries_in_spanish = dict(countries_for_language('es'))`
`countries_in_spanish.get('HK')`
 returns '**RAE de Hong Kong (China)**' , note the spelling and parenthesis.

> Now i would like to get back the country code '**HK**' by using '**RAE de Hong Kong (China)**'    

something like this:
`codes_for_spanish_countries = dict(codes_for_language('es'))`
`codes_for_spanish_countries.get('RAE de Hong Kong (China)')`

I know I can get it using code acrobatics to get the country code using the index, by turning keys() and values() into lists, like this:

```
def get_alpha_2_from_country_name_in_spanish(country_name):
    """ 
    Get country alpha_2 code by Spanish country name.
    Use country name with same exact spelling as the country_list library.
    returns '' empty string if name not found.
    """

    countries = dict(countries_for_language('ES'))
    codes = list(countries.keys())
    names = list(countries.values())
    try:
        position = names.index(country_name)
    except:
        return ''
    
    return codes[position]
```
But I'd rather not reinvent the wheel if this is already built in to your library, is it?

Thanks!

**Comment by bulv1ne** [comment]
Hi, fun of you using this library!

`countries_for_language` returns a list of tuples [country code, country name], calling `dict(countries_for_language('es'))` will automatically use the country code as key, and country name as value.
```python
countries_in_spanish = dict(codes_for_language('es'))
# Is the same as:
countries_in_spanish = {code: name for code, name in countries_for_language('es')}
```

If you want the opposite, you can do the following instead:
```python
codes_for_spanish_countries = {name: code for code, name in countries_for_language('es')}
```
Then the `codes_for_spanish_countries` will be a dictionary where the country name is the key, and country code is the value.

Giving the following result:
```python
>>> codes_for_spanish_countries.get('RAE de Hong Kong (China)')
'HK'
```

**Comment by Avramo** [comment]
That's much shorter and cleaner.
Thanks for the answer.
I see you also updated the Readme, good job!

p.s. In your answer I believe you meant `countries_for_language`, not `codes_for_language `.
